### PR TITLE
Formatted Update kv.js

### PR DESCRIPTION
**Pull request by miguelgargallo**
Formatted Update kv.js

### CODE REVIEW

**Comment by jelveh** [comment]
Thanks for the PR. Could you explain what the purpose of it is?

**Comment by miguelgargallo** [comment]
The objective is to enhance the code's readability, enabling new developers to quickly grasp and modify it as necessary. I admire your project and, during our free time at university, my fellow students and I aimed to make it accessible to others.

**Comment by KernelDeimos** [comment]
Indentation level is a matter of preference until we find a scientific study that suggests one is better another. I think we should keep it at 4 spaces because that's our convention elsewhere. Would you be open to separating other changes from the indentation change?

**Comment by jelveh** [comment]
@miguelgargallo thanks again for the PR. Would you be able to break this down into two PR's for review: 1) formatting changes 2) other changes.

In the meantime, I'm going to close this PR.

**Pull request closed without merging**
