### PR TITLE
Fix options and add unit tests

### PR DESCRIPTION
**Pull request by KernelDeimos**
Note: number of additions isn't accurate because it's counting `package-lock.json` as well.

### CODE REVIEW

**Comment by jelveh** [comment]
Thanks for the PR. Can you add some more comments to `Options.js`, explaining how and what it does?

**Comment by KernelDeimos** [comment]
> Thanks for the PR. Can you add some more comments to `Options.js`, explaining how and what it does?

Added some documentation. Also something else came to mind though; while the format of `set('key', 'value', ['OPTION_1', 'OPTION_2', 123])` more closely matches what it would look like as a Redis command, maybe it makes sense to favor the language constructs over this. For example: `set('key', 'value', { OPTION_1: true, OPTION_2: 123 })` instead.

What are your thoughts?

**Comment by jelveh** [comment]
I agree. Let's scrap Redis's way of handling and go all JS.

**Comment by jelveh** [comment]
We're going to proceed with handling options The JavaScript Way™.

**Pull request closed without merging**
